In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    "date": [
        "2025-01-01", "2025-01-02", "2025-01-03",
        "2025-01-05", "2025-01-06",
        "2025-01-09", "2025-01-10"
    ],
    "revenue": [1200, 1300, 1250, 1400, 1500, 1600, 1550]
}
 
df = pd.DataFrame(data)
df

         date  revenue
0  2025-01-01     1200
1  2025-01-02     1300
2  2025-01-03     1250
3  2025-01-05     1400
4  2025-01-06     1500
5  2025-01-09     1600
6  2025-01-10     1550

In [3]:
df.dtypes

date         str
revenue    int64
dtype: object

In [4]:
df['date'] = pd.to_datetime(df['date'])
df.dtypes

date       datetime64[us]
revenue             int64
dtype: object

In [5]:
df["date_str"] = df["date"].dt.strftime("%Y-%m-%d")
df

        date  revenue    date_str
0 2025-01-01     1200  2025-01-01
1 2025-01-02     1300  2025-01-02
2 2025-01-03     1250  2025-01-03
3 2025-01-05     1400  2025-01-05
4 2025-01-06     1500  2025-01-06
5 2025-01-09     1600  2025-01-09
6 2025-01-10     1550  2025-01-10

In [6]:
df["year"] = df["date"].dt.year
df["month"] = df["date"].dt.month
df["day"] = df["date"].dt.day
df["weekday"] = df["date"].dt.day_name()
 
df

        date  revenue    date_str  year  month  day    weekday
0 2025-01-01     1200  2025-01-01  2025      1    1  Wednesday
1 2025-01-02     1300  2025-01-02  2025      1    2   Thursday
2 2025-01-03     1250  2025-01-03  2025      1    3     Friday
3 2025-01-05     1400  2025-01-05  2025      1    5     Sunday
4 2025-01-06     1500  2025-01-06  2025      1    6     Monday
5 2025-01-09     1600  2025-01-09  2025      1    9   Thursday
6 2025-01-10     1550  2025-01-10  2025      1   10     Friday

In [7]:
df["prev_date"] = df["date"].shift(1)
df["days_since_prev"] = df["date"] - df["prev_date"]
 
df

,date,revenue,date_str,year,month,day,weekday,prev_date,days_since_prev
0,2025-01-01,1200,2025-01-01,2025,1,1,Wednesday,NaT,NaT
1,2025-01-02,1300,2025-01-02,2025,1,2,Thursday,2025-01-01,1 days
2,2025-01-03,1250,2025-01-03,2025,1,3,Friday,2025-01-02,1 days
3,2025-01-05,1400,2025-01-05,2025,1,5,Sunday,2025-01-03,2 days
4,2025-01-06,1500,2025-01-06,2025,1,6,Monday,2025-01-05,1 days
5,2025-01-09,1600,2025-01-09,2025,1,9,Thursday,2025-01-06,3 days
6,2025-01-10,1550,2025-01-10,2025,1,10,Friday,2025-01-09,1 days

In [8]:
# Nustatomas laiko indeksas
ts = df.set_index("date")[["revenue"]]
 
# Sukuriama pilna dienų seka
ts_daily = ts.asfreq("D")
ts_daily

            revenue
date
2025-01-01   1200.0
2025-01-02   1300.0
2025-01-03   1250.0
2025-01-04      NaN
2025-01-05   1400.0
2025-01-06   1500.0
2025-01-07      NaN
2025-01-08      NaN
2025-01-09   1600.0
2025-01-10   1550.0

In [10]:
# Paprastas trūkstamų reikšmių tvarkymas
ts_daily["revenue_filled"] = ts_daily["revenue"].fillna(0)
ts_daily

            revenue  revenue_filled
date
2025-01-01   1200.0          1200.0
2025-01-02   1300.0          1300.0
2025-01-03   1250.0          1250.0
2025-01-04      NaN             0.0
2025-01-05   1400.0          1400.0
2025-01-06   1500.0          1500.0
2025-01-07      NaN             0.0
2025-01-08      NaN             0.0
2025-01-09   1600.0          1600.0
2025-01-10   1550.0          1550.0

In [11]:
# Savaitinis agregavimas
weekly = ts_daily["revenue"].resample("W").sum()
weekly

date
2025-01-05    5150.0
2025-01-12    4650.0
Freq: W-SUN, Name: revenue, dtype: float64

In [13]:
# Mėnesinis vidurkis
monthly_avg = ts_daily["revenue"].resample("ME").mean()
monthly_avg

date
2025-01-31    1400.0
Freq: ME, Name: revenue, dtype: float64