In [2]:
import pandas as pd
import numpy as np

# Assignment 1: DataFrame Basics

Hi there!

Can you read in the transactions dataset and report on:

* The number of rows and columns
* The names of the columns
* The datatypes of each column

In [3]:
# A common practice is to create a path variable to pass to read_csv
path = r"C:\Users\Itanas\Desktop\Python/transactions.csv"
df = pd.read_csv(path)

In [4]:
df.shape

(83488, 3)

In [5]:
df.columns

Index(['date', 'store_nbr', 'transactions'], dtype='str')

In [6]:
df.dtypes

date              str
store_nbr       int64
transactions    int64
dtype: object

In [7]:
df['date'] = pd.to_datetime(df['date'])
df.dtypes

date            datetime64[us]
store_nbr                int64
transactions             int64
dtype: object

# Assignment 2: Exploring DataFrames

Hello!

* Can you quickly inspect the first 5 rows of the transactions data? 

* Then, dive a bit more deeply into the data and check if there are any missing values.
* What about the number of unique dates? I want to make sure we didn’t leave any out.
* Finally, can you report the mean, median, min and max of “transactions”?  I want to check for any anomalies in our data.

In [8]:
df.head()

        date  store_nbr  transactions
0 2013-01-01         25           770
1 2013-01-02          1          2111
2 2013-01-02          2          2358
3 2013-01-02          3          3487
4 2013-01-02          4          1922

In [9]:
df.isna().values.any()

np.False_

In [10]:
df['date'].nunique()

1682

In [11]:
df.describe().T

,count,mean,min,25%,50%,75%,max,std
date,83488,2015-05-20 16:07:40.866232,2013-01-01 00:00:00,2014-03-27 00:00:00,2015-06-08 00:00:00,2016-07-14 06:00:00,2017-08-15 00:00:00,NaN
store_nbr,83488.0,26.939237,1.0,13.0,27.0,40.0,54.0,15.608204
transactions,83488.0,1694.602158,5.0,1046.0,1393.0,2079.0,8359.0,963.286644

In [12]:
print(df['transactions'].mean().round(2))
print(df['transactions'].median())
print(df["transactions"].min())
print(df["transactions"].max())

1694.6
1393.0
5
8359

In [13]:
df.duplicated().sum()

np.int64(0)

# Exercise 3 - Accessing DataFrames

Hi, starting to dive deeper into this data.

I noticed that the first row is the only one from 2013-01-01.

* Can you get me a copy of the DataFrame that excludes that row, and only includes “store_nbr” and “transactions”?
* Also, can you report the number of unique store numbers?
* Finally, return the total number of transactions in millions

In [14]:
df.head()

        date  store_nbr  transactions
0 2013-01-01         25           770
1 2013-01-02          1          2111
2 2013-01-02          2          2358
3 2013-01-02          3          3487
4 2013-01-02          4          1922

In [15]:
df_new = df.drop('date', axis=1)
df_new

       store_nbr  transactions
0             25           770
1              1          2111
2              2          2358
3              3          3487
4              4          1922
...          ...           ...
83483         50          2804
83484         51          1573
83485         52          2255
83486         53           932
83487         54           802

[83488 rows x 2 columns]

In [16]:
count = df_new['store_nbr'].nunique()
print(f"unique stores: {count}")

unique stores: 54

In [17]:
transaction_sum = df_new['transactions'].sum()
transaction_sum_mln = transaction_sum / 1e6
print(f"Total transactions: {transaction_sum_mln} million")

Total transactions: 141.478945 million

# Assignment 4: Dropping Data and Duplicates

Hi there!

Can you:

1. Drop the first row of data? We want it permanently removed. 
2. Drop the date column but not in place
3. Return a dataframe that only includes the last row for each of the stores.

Thanks!

In [18]:
df.head()

        date  store_nbr  transactions
0 2013-01-01         25           770
1 2013-01-02          1          2111
2 2013-01-02          2          2358
3 2013-01-02          3          3487
4 2013-01-02          4          1922

In [19]:
df = df.iloc[1:].reset_index(drop=True)
df

            date  store_nbr  transactions
0     2013-01-02          1          2111
1     2013-01-02          2          2358
2     2013-01-02          3          3487
3     2013-01-02          4          1922
4     2013-01-02          5          1903
...          ...        ...           ...
83482 2017-08-15         50          2804
83483 2017-08-15         51          1573
83484 2017-08-15         52          2255
83485 2017-08-15         53           932
83486 2017-08-15         54           802

[83487 rows x 3 columns]

In [20]:
df_clean = df.drop('date', axis=1)
df_clean

       store_nbr  transactions
0              1          2111
1              2          2358
2              3          3487
3              4          1922
4              5          1903
...          ...           ...
83482         50          2804
83483         51          1573
83484         52          2255
83485         53           932
83486         54           802

[83487 rows x 2 columns]

In [21]:
df.drop_duplicates(subset='store_nbr', keep='last').head()

            date  store_nbr  transactions
83433 2017-08-15          1          1693
83434 2017-08-15          2          1737
83435 2017-08-15          3          2956
83436 2017-08-15          4          1283
83437 2017-08-15          5          1310

In [ ]:
last_transaction = df.groupby('store_nbr').tail(1)
last_transaction

# Assignment 5: Missing Data

Hello, 

Can you tell if any dates or prices are missing in the oil dataset?

Then compare the mean of the oil series when filling in with mean vs. filling in with 0.

Thanks!

In [23]:
oil = pd.read_csv(r"C:\Users\Itanas\Desktop\Python/oil.csv")

In [24]:
oil.isna().sum()

date           0
dcoilwtico    43
dtype: int64

In [ ]:
original_mean = oil['dcoilwtico'].mean()

mean_filled_mean = oil['dcoilwtico'].fillna(original_mean).mean()
zero_filled_mean = oil['dcoilwtico'].fillna(0).mean()

print(f"Original Mean (ignoring NaNs): {original_mean:.4f}")
print(f"Mean after filling with mean: {mean_filled_mean:.4f}")
print(f"Mean after filling with zero: {zero_filled_mean:.4f}")

diff = original_mean - zero_filled_mean
print(f"The difference when filling with 0 is: {diff:.4f}")

Original Mean (ignoring NaNs): 67.7144
Mean after filling with mean: 67.7144
Mean after filling with zero: 65.3238
The difference when filling with 0 is: 2.3906

# Assignment 6: Filtering DataFrames

I need some quick research on store 25:

* First, calculate the percentage of times ALL stores had more than 2000 transactions
* Then, calculate the percentage of times store 25 had more than 2000 transactions, and calculate the sum of transactions on these days
* Finally, sum the transactions for stores 25 and 31, that occurred in May or June, and had less than 2000 transactions

In [26]:
df.head()

        date  store_nbr  transactions
0 2013-01-02          1          2111
1 2013-01-02          2          2358
2 2013-01-02          3          3487
3 2013-01-02          4          1922
4 2013-01-02          5          1903

In [27]:
daily_total = df.groupby('date')['transactions'].sum()
days_above_2000 = (daily_total > 2000).sum()
total_days = df['date'].nunique()
percentage = (days_above_2000 / total_days) * 100
print(f"Percentage of days when total transactions were > 2000: {percentage:.2f}%")

Percentage of days when total transactions were > 2000: 99.88%

In [31]:
store_25_df = df[df['store_nbr'] == 25]
mask_above_2000 = store_25_df['transactions'] > 2000
days_more_2000 = mask_above_2000.sum()

total_days_25_store = len(store_25_df)
percentage_25 = (days_more_2000 / total_days_25_store) * 100 
sum_transactions_25 = store_25_df.loc[mask_above_2000, 'transactions'].sum()

print(f"Store 25 had more than 2000 transactions on {percentage_25:.2f}% of its days.")
print(f"The total sum of transactions on those days is: {sum_transactions_25:,}")

Store 25 had more than 2000 transactions on 3.47% of its days.
The total sum of transactions on those days is: 144,903

In [35]:
mask_stors = df['store_nbr'].isin([25, 31])
mask_months = df['date'].dt.month.isin([5, 7])
mask_transactions = df['transactions'] > 2000
final_mask = mask_stors & mask_months & mask_transactions
sum_transactions = df.loc[final_mask, 'transactions'].sum()

print(f"The sum of transactions for the specified criteria is: {sum_transactions:,.2f}")

The sum of transactions for the specified criteria is: 8,588.00

# Assignment 7: Sorting DataFrames

Hi there,
* Can you get me a dataset that includes the 5 days with the highest transactions counts? Any similarities between them?
* Then, can you get me a dataset sorted by date from earliest to most recent, but with the highest transactions first and the lowest transactions last for each day?
* Finally, sort the columns in reverse alphabetical order. 

Thanks!

In [36]:
df.head()

        date  store_nbr  transactions
0 2013-01-02          1          2111
1 2013-01-02          2          2358
2 2013-01-02          3          3487
3 2013-01-02          4          1922
4 2013-01-02          5          1903

# Assignment 8: Modifying Columns

Just some quick work, but can you send me the transaction data with the columns renamed?

* Rename `transactions` to `transaction_count` and `store_nbr` to `store_number`.
* Reorder the columns so date is first, then store number, then transaction count.

Thanks!

In [ ]:
transactions.head()

# Assignment 9: Column Creation

Just some quick work, but can you send me the transaction data with the columns renamed?

* Create a `pct_to_target` column that divides transactions by 2500.
* Then, create a `met_target` column that returns True if `pct_to_target` is greater than or equal to 1.
* Next, create a `bonus_payable` column that equals 100 if `met_target` is True, and 0 if not. Then sum the bonus payable column.
* Finally, create columns for month and day of week as integers. There is some helper code for these dateparts below.



Thanks!

In [ ]:
transactions.head()

# Assignment 10: np.select

Hi there! I need a few columns created.

1. Create a ‘seasonal_bonus’ column that applies to these dates: 
    * All days in December (month = 12)
    * Sundays (day_of_week = 6) in May (month = 5)
    * Mondays (day_of_week = 0) in July (month = 7)
2. Call the December bonus ‘Holiday Bonus’, the May bonus ‘Corporate Month’, and the July bonus ‘Summer Special’. If no bonus applies, the column should display ‘None’. 
3. Finally, calculate the total bonus owed at $100 per day.

Thanks!

In [ ]:
transactions.head()

# Assignment 11: Assign 

* Drop the columns that have been created so far (keep only date, store_number, and transaction count), and recreate them using the assign method.
* Then sum the seasonal bonus owed once again to make sure the numbers are correct.

In [ ]:
# Drop columns we created in prior exercises

In [ ]:
# Create same columns with assign

# Assignment 12: Memory Optimization

Reduce the memory usage of the transactions DataFrame to below 5MB.

In [ ]:
transactions.head()

In [ ]:
transactions.info(memory_usage="deep")